repos:
  - repo: local
    hooks:
      - id: gdscript-formatter
        name: gdscript-formatter
        description: "formatter for GDScript"
        entry: ./.tools/gdscript-formatter
        language: system
        require_serial: true
        types: [gdscript]

      - id: gdscript-linter
        name: gdscript-linter
        description: "linter for GDScript"
        entry: ./.tools/gdscript-formatter lint --pretty || true
        language: system
        require_serial: true
        types: [gdscript]
