name: Build and Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    needs:
      - compute-version
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login into ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build builder image
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          target: builder-base
          tags: builder-base:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/builder-base:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/builder-base:cache,mode=max
          push: false
          load: true

      - name: Build Desktop
        run: |
          mkdir .dist
          echo "::group::Build Windows Desktop"
          docker run --rm \
            -v ${GITHUB_WORKSPACE}:/GIGABAH \
            -w /GIGABAH \
            builder-base:latest \
            sh -c "godot --headless --verbose --export-release 'Windows Desktop'"
          echo "::endgroup::"
          echo "::group::Build Linux Desktop"
          docker run --rm \
            -v ${GITHUB_WORKSPACE}:/GIGABAH \
            -w /GIGABAH \
            builder-base:latest \
            sh -c "godot --headless --verbose --export-release 'Linux Desktop'"
          echo "::endgroup::"
          echo "::group::Build Mac OS Desktop"
          docker run --rm \
            -v ${GITHUB_WORKSPACE}:/GIGABAH \
            -w /GIGABAH \
            builder-base:latest \
            sh -c "godot --headless --verbose --export-release 'macOS Desktop'"
          echo "::endgroup::"
          ls -lh ./.dist

      - name: Upload build Desktop artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-desktop-output
          path: .dist
          if-no-files-found: "error"
          include-hidden-files: "true"

      - name: Build Dedicated Server
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/builder-base:cache
          push: false
          tags: |
            ghcr.io/${{ github.repository }}:${{ needs.compute-version.outputs.ver }}
            ${{ needs.compute-version.outputs.release == 'true' && format('ghcr.io/{0}:latest', github.repository) || '' }}

  release-call:
    needs: build
    uses: ./.github/workflows/release.yml
