name: Lint

on:
  push:
    branches:
      - main
      - release

jobs:
  pre-commit:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v5

        - name: Set up Python
          uses: actions/setup-python@v6
          with:
            python-version: '3.x'

        - name: Install pre-commit
          run: |
            python -m pip install pre-commit
            python -m pip freeze --local

        - name: Run pre-commit gdlint
          uses: ./.github/actions/pre-commit
          with:
            extra_args: "gdlint --all-files"
          continue-on-error: true

        - name: Run pre-commit gdformat
          uses: ./.github/actions/pre-commit
          with:
            extra_args: "gdformat --all-files"

  build:
    needs: pre-commit
    uses: ./.github/workflows/build.yml
    with:
      event_name: ${{ github.event_name }}
