name: Build and Release

on:
  workflow_call:

jobs:
  compute-version:
    runs-on: ubuntu-latest

    steps:
      - name: Compute version and release type
        id: version
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VER="${GITHUB_REF_NAME}"
            RELEASE="true"
          else
            VER="${GITHUB_SHA::8}"
            RELEASE="true"
          fi
          echo "VER=$VER"
          echo "ver=$VER" >> $GITHUB_OUTPUT
          echo "RELEASE=$RELEASE"
          echo "release=$RELEASE" >> $GITHUB_OUTPUT

    outputs:
      ver: ${{ steps.version.outputs.ver  }}
      release: ${{ steps.version.outputs.release }}
